### PR TITLE
Marlin tools

### PR DESCRIPTION
**Pull request by thomdixon**
Implemented two tools (and a trivial library) in Ruby for working with Marlin instances.
- `verify-integrity.rb` ensures both that the files listed by `/all` are on disk in the expected place and that the SHA-1 and filesize in redis match those of the files on disk.
- `verify-consistency.rb` ensures that the list returned by `/all` on two (or more) different Marlin endpoints are the same, and that the file attributes returned by `/<filename>/all` match on all the provided endpoints.

Check out the README for usage information. Please let me know if you run into issues while testing prior to merging.

Cheers,
Thom

### CODE REVIEW

**Comment by mediocregopher** [comment]
Awesome! I like the code, it's really straightforward. My only comment is that I'd like to leave out having to have any outside dependencies, since that adds a step when deploying, and the only thing I see needing an outside dep is the edn stuff. I appreciate that you added that in, it's a good idea, but for this case I think ease-of-deployment outweighs being able to use it.

Other than that, awesome work! Will totally merge this in.

**Comment by mediocregopher** [comment]
Actually, one more comment. I know I said put it in `support`, but could you make it be in `support/verify` or something like that? Since they're not standalones I think we should group them with the library they need (the `marlin.rb` file)

**Comment by thomdixon** [comment]
Cool! I'll
- strip out the Marlin-config-file-related code
- dump the `Gemfile` and its `lock` (and thus the `edn` dependency) and then
- move everything into `support/verify`

when I get a chance.

Hilariously enough, the well-written edn library is the only reason I chose Ruby over Python--all the edn modules for Python crashed and burned on the Marlin config files.

Cheers,
Thom

**Comment by mediocregopher** [comment]
aw man, I'm sorry :(

**Comment by thomdixon** [comment]
No big deal--it was fun, and I learned a lot about Ruby. :) It also wouldn't be too much of a hassle to rewrite in Python or Perl, if you preferred that direction.

Cheers,
Thom

**Pull request closed without merging**
